"""
Extraction-helper utility functions.
"""

import subprocess
import numpy as np
from ruamel.yaml import YAML
yaml = YAML(typ='safe', pure=True)
from os import system
from pathlib import Path
from tqdm.auto import tqdm
from moseq2_extract.util import read_yaml
from moseq2_extract.extract.extract import extract_chunk
from moseq2_extract.helpers.data import check_completion_status
from moseq2_extract.io.video import load_movie_data, write_frames_preview


def write_extracted_chunk_to_h5(
    h5_file, results, config_data, scalars, frame_range, offset
):
    """

    Write extracted frames, frame masks, and scalars to an open h5 file.

    Args:
    h5_file (H5py.File): open results_00 h5 file to save data in.
    results (dict): extraction results dict.
    config_data (dict): dictionary containing extraction parameters (autogenerated)
    scalars (list): list of keys to scalar attribute values
    frame_range (range object): current chunk frame range
    offset (int): frame offset

    Returns:
    """
    def _write_h5(name, data: np.ndarray):
        """Write data after offset to h5 file."""
        h5_file[name][frame_range] = data[offset:]

    # Writing computed scalars to h5 file
    for scalar in scalars:
        _write_h5(f"scalars/{scalar}", results["scalars"][scalar])

    # Writing frames and mask to h5
    _write_h5("frames", results["depth_frames"])
    _write_h5("frames_mask", results["mask_frames"])

    # Writing flip classifier results to h5
    if config_data["flip_classifier"]:
        _write_h5("metadata/extraction/flips", results["flips"])


def set_tracking_model_parameters(
    results, min_height, tracking_model_ll_clip, chunk_overlap, **kwargs
):
    """
    Threshold and clip the masked frame data if use_tracking_model = True and update results.

    Args:
    results (dict): dict of extracted depth frames and mask frames to threshold to update; output of extract_chunk().
    min_height (int): distance from floor to threshold out of extracted image.
    tracking_model_ll_clip (numpy.ndarray): clipped frame regions based on EM loglikelihoods computed in extract_chunk().
    chunk_overlap (int): number of frames each extracted chunk is overlapping with the next.

    Returns:
    results (dict): updated results dict with thresholded and clipped mask_frames.
    tracking_init_mean (float): mean value for EM Tracking
    tracking_init_cov (float): covariance value for EM Tracking
    """

    # Thresholding and clipping EM-tracked frame mask data
    results["mask_frames"][
        results["depth_frames"] < min_height
    ] = tracking_model_ll_clip
    results["mask_frames"][
        results["mask_frames"] < tracking_model_ll_clip
    ] = tracking_model_ll_clip

    # Updating EM tracking estimators
    tracking_init_mean = results["parameters"]["mean"][-(chunk_overlap + 1)]
    tracking_init_cov = results["parameters"]["cov"][-(chunk_overlap + 1)]

    return results, tracking_init_mean, tracking_init_cov


def make_output_movie(results, config_data, offset=0):
    """
    Create an array for output movie with filtered video and cropped mouse on the top left

    Args:
    results (dict): dict of extracted depth frames, and original raw chunk to create an output movie.
    config_data (dict): dict of extraction parameters containing the crop sizes used in the extraction.
    offset (int): current offset being used, automatically set if chunk_overlap > 0

    Returns:
    output_movie (numpy.ndarray): output movie to write to mp4 file.
    """

    # Create empty array for output movie with filtered video and cropped mouse on the top left
    nframes, rows, cols = results["chunk"][offset:].shape
    output_movie = np.zeros(
        (
            nframes,
            rows + config_data["crop_size"][0],
            cols + config_data["crop_size"][1],
        ),
        "uint16",
    )

    # Populating array with filtered and cropped videos
    output_movie[:, : config_data["crop_size"][0], : config_data["crop_size"][1]] = (
        results["depth_frames"][offset:]
    )
    output_movie[:, config_data["crop_size"][0] :, config_data["crop_size"][1] :] = (
        results["chunk"][offset:]
    )

    return output_movie


def process_extract_batches(
    input_file,
    config_data,
    bground_im,
    roi,
    frame_batches,
    str_els,
    output_mov_path,
    scalars=None,
    h5_file=None,
    video_pipe=None,
    **kwargs,
):
    """
    Compute extracted frames and save them to h5 files and avi files.

    Args:
    input_file (str): path to depth file
    config_data (dict): dictionary containing extraction parameters (autogenerated)
    bground_im (numpy.ndarray):  background image
    roi (numpy.ndarray): roi image
    frame_batches (list): list of batches of frames to serially process.
    str_els (dict): dictionary containing OpenCV StructuringElements
    output_mov_path (str): path and filename of the output movie generated by the extraction
    scalars (list): list of keys to scalar attribute values
    h5file (h5py.File): opened h5 file to write extracted batches to
    video_pipe (subprocess.PIPE): open pipe to location where preview extraction is being written.
    kwargs (dict): Extra keyword arguments.

    Returns:
    """

    tracking_init_mean = config_data.pop("tracking_init_mean", None)
    tracking_init_cov = config_data.pop("tracking_init_cov", None)

    for i, frame_range in enumerate(tqdm(frame_batches, desc="Processing batches")):
        raw_chunk = load_movie_data(
            input_file, frame_range, frame_size=bground_im.shape[::-1], **config_data
        )

        offset = config_data["chunk_overlap"] if i > 0 else 0

        # Get crop-rotated frame batch
        results = extract_chunk(
            **config_data,
            **str_els,
            chunk=raw_chunk,
            roi=roi,
            bground=bground_im,
            tracking_init_mean=tracking_init_mean,
            tracking_init_cov=tracking_init_cov,
        )

        if config_data["use_tracking_model"]:
            # threshold and clip mask frames from EM tracking results
            results, tracking_init_mean, tracking_init_cov = (
                set_tracking_model_parameters(results, **config_data)
            )

        # Offsetting frame chunk by CLI parameter defined option: chunk_overlap
        frame_range = frame_range[offset:]

        if h5_file is not None:
            write_extracted_chunk_to_h5(
                h5_file, results, config_data, scalars, frame_range, offset
            )

        # Create array for output movie with filtered video and cropped mouse on the top left
        output_movie = make_output_movie(results, config_data, offset)

        # Writing frame batch to mp4 file
        video_pipe = write_frames_preview(
            output_mov_path,
            output_movie,
            pipe=video_pipe,
            close_pipe=False,
            fps=config_data["fps"],
            frame_range=list(frame_range),
            depth_max=config_data["max_height"],
            depth_min=config_data["min_height"],
            progress_bar=config_data.get("progress_bar", False),
        )

    # Check if video is done writing. If not, wait.
    if video_pipe is not None:
        video_pipe.communicate()


def run_local_extract(to_extract, config_file, skip_extracted=False):
    """
    Run the extract command on given list of sessions to extract on a local platform.

    Args:
    to_extract (list): list of paths to files to extract
    config_file (str): path to configuration file containing pre-configured extract and ROI
    skip_extracted (bool): Whether to skip already extracted session.

    """
    from moseq2_extract.gui import extract_command

    for ext in tqdm(to_extract, desc="Extracting Sessions"):
        try:
            extract_command(ext, None, config_file=config_file, skip=skip_extracted)
        except Exception as e:
            print("Unexpected error:", e)
            print("could not extract", ext)


def run_slurm_extract(input_dir, to_extract, config_data, skip_extracted=False):

    assert (
        "extract_out_script" in config_data
    ), "Need to supply extract_out_script to save extract commands"
    # expand input_dir absolute path
    input_dir = Path(input_dir).absolute()

    # make session_specific config file and save it in proc folder if session config exists
    if Path(config_data.get("session_config_path", "")).exists():
        session_configs = read_yaml(config_data["session_config_path"])
        for depth_file in map(Path, to_extract):
            output_file = depth_file.parent / config_data["output_dir"] / "config.yaml"

            # ensure output_dir exists
            output_file.parent.mkdir(parents=True, exist_ok=True)

            # get and write session-specific parameters
            session_key = depth_file.parent.name

            with open(output_file, "w") as f:
                yaml.dump(session_configs.get(session_key, config_data), f)

    # Construct sbatch command for slurm
    commands = ""
    for depth_file in map(Path, to_extract):
        output_dir = depth_file.parent / config_data["output_dir"]

        # skip session if skip_extracted is true and the session is already extracted
        if skip_extracted and check_completion_status(
            output_dir / "results_00.yaml"
        ):
            continue

        # set up config file
        if Path(config_data.get("session_config_path", "")).exists():
            config_file = output_dir / "config.yaml"
        else:
            config_file = Path(config_data["config_file"])

        # construct command
        base_command = (
            f'moseq2-extract --config-file {config_file} extract {depth_file}; "\n'
        )
        prefix = f'sbatch -c {config_data["ncpus"] if config_data["ncpus"] > 0 else 1} --mem={config_data["memory"]} '
        prefix += f'-p {config_data["partition"]} -t {config_data["wall_time"]} --wrap "{config_data["prefix"]}'
        commands += prefix + base_command

    # Ensure output directory exists
    config_data["extract_out_script"] = input_dir / config_data["extract_out_script"]
    with open(config_data["extract_out_script"], "w") as f:
        f.write(commands)
    print("Commands saved to:", config_data["extract_out_script"])

    # Print command
    if config_data["get_cmd"]:
        print("Listing extract commands...\n")
        print(commands)

    # Run command using system
    if config_data["run_cmd"]:
        print("Running extract commands")
        subprocess.run(commands, shell=True, check=True)
        # system(commands)
