[extract]
# TODO: organize by subcommand

# general commands

# background and arena mask commands

# extraction-specific commands

# batch-specific commands
progress_bar = false
recompute_bg = false
use_plane_bground = false
output_dir = "proc"
noise_tolerance = 30
erode_iterations = 0
bg_v2 = true
bg_roi_erode = [ 1, 1 ]
dilate_iterations = 1
bg_roi_sort_by_area = false
bg_roi_fill_holes = true
bg_roi_gradient_kernel = 7
bg_roi_gradient_threshold = 3000
bg_roi_gradient_filter = false
bg_roi_depth_range = [ 650, 750 ]
manual_set_depth_range = false
camera_type = "auto"
bg_roi_weights = [ 1.0, 0.1, 1.0 ]
bg_roi_index = 0
bg_roi_shape = "ellipse"
bg_roi_dilate = [ 10, 10 ]
mapping = "DEPTH"
threads = 8
delete = false
fps = 30
chunk_size = 3000
skip_completed = false
compress_threads = 3
compress_chunk_size = 3000
compress = false
frame_trim = [ 0, 0 ]
model_smoothing_clips = [ 0, 0 ]
angle_hampel_sig = 3
angle_hampel_span = 0
centroid_hampel_sig = 3
centroid_hampel_span = 0
pixel_format = "gray16le"
movie_dtype = "<i2"
frame_dtype = "uint8"
write_movie = true
chunk_overlap = 0
temporal_filter_size = [ 0 ]
spatial_filter_size = [ 3 ]
tail_filter_shape = "ellipse"
tail_filter_size = [ 9, 9 ]
tail_filter_iters = 1
cable_filter_size = [ 5, 5 ]
cable_filter_shape = "rectangle"
cable_filter_iters = 0
tracking_model_init = "raw"
tracking_model_segment = true
tracking_model_ll_clip = -100
tracking_model_mask_threshold = -16
tracking_model_ll_threshold = -100
use_tracking_model = false
use_cc = false
flip_classifier_smoothing = 51
compute_raw_scalars = false
detected_true_depth = "auto"
max_height = 120
min_height = 10
crop_size = [ 80, 80 ]